### PR TITLE
Change opencollective to contributors-img

### PR DESCRIPTION
**Pull request by FantasqueX**
Details are described in #481

### CODE REVIEW

**Comment by iromise** [comment]
@FantasqueX I haven't taken a close look at the contributors-img. Is there some big difference between opencollective and contributors-img?

**Comment by iromise** [comment]
@FantasqueX It seems good, but I find that the figure generated is not beautiful as well as opencollective. Besides, it is too large.

**Comment by FantasqueX** [comment]
@iromise That's quite a problem :(

**Comment by arttnba3** [comment]
@iromise It's okay that the picture is not beautiful enough, as the correct result does mean to be more important than a look. We can just change to `contributors-img` temporarily, and find the one with better look in the future when we have spare time to do so.

**Comment by arttnba3** [comment]
Hi FantasqueX,

Thanks for your contributions! This plugin dose work well and I'm going to merge your pull request. This is just a notification message, and you don't need to take further actions to respond.

If you have any questions, or if you have further concerns, please feel free to contact us.

Best regards,
arttnba3
04/10/2024

**Pull request merged**
