### PR TITLE
A very initial Dockerfile to view ctf-wiki at local.

### PR DESCRIPTION
**Pull request by summershrimp**
ATT.
Just build and serve using lighttpd. Still need to change CDN resource to local. Please create a new issue for me if accepted.
And I also created a docker hub organization called ctfwiki (hyphen is not allowed by docker hub), more member need to be added.
`docker run -d xm1994/ctf-wiki:add-dockerfile` and will run it now.

### CODE REVIEW

**Comment by iromise** [comment]
GOOD IDEA! could you please add some description in readme?

**Comment by summershrimp** [comment]
I've updated the `README.md`. Could you please add me to this project once this PR merge, and I can create automated build at docker hub, or give me someone else's docker hub account, I'll add it to the `ctfwiki` organization at docker hub.

**Comment by iromise** [comment]
@summershrimp already added.

**Comment by summershrimp** [comment]
I still can't see ctf-wiki at docker hub. maybe privileges issue. Give me your docker hub account? @iromise

**Comment by iromise** [comment]
@summershrimp  Already give you on the bearychat(iromise), but I cannot search it on dockerhub.

**Pull request merged**
