### PR TITLE
Fix outdated ref link in  basic-contribute-approach

### LINKED ISSUE #747: 基本贡献方式中的Github使用参考链接已失效
https://github.com/ctf-wiki/ctf-wiki/blob/master/docs/zh/docs/contribute/basic-contribute-approach.md
> 如果还是不放心，可以参考这篇文章：https://juejin.im/entry/56e638591ea49300550885cc

该链接已失效(404)。

### PR DESCRIPTION
**Pull request by iczc**
Closes #747

### CODE REVIEW

**Comment by bash-c** [comment]
Thanks for your contribution @iczc 

However, I think there should be a discussion about this.
@iromise Should we use an external link further? I think it's better to make a local backup in case of any possible invalid link in the future.

**Comment by iromise** [comment]
@iczc @bash-c Yeah, we'd better use a local version. But for this kind of information, maybe we could find some stable links, e.g., github's official introduction.

**Comment by iczc** [comment]
@iromise Is this link appropriate following?
https://guides.github.com/activities/hello-world/

**Comment by iromise** [comment]
@iczc  maybe we can also add this link https://guides.github.com/activities/forking/ as the reader need to know fork and pr.

**Pull request merged**
