### PR TITLE
Add an example of junk code in junk-code.md and improve the expression.

### PR DESCRIPTION
**Pull request by Mz1z**
If there is any mistakes I make, please tell me and I would like to amend it.
Thank you very much.

### CODE REVIEW

**Comment by iromise** [comment]
@Mz1z You can type a space between Chinese character and English character, e.g., `下面以 VC 添加花指令的方式举例`.

**Comment by iromise** [comment]
I am sorry that I can no reply fast recently as I am a little busy...

**Comment by Mz1z** [comment]
@iromise Thank you for replying in your busy schedule. I have added space between Chinese and English Characters.
If there is anything needed to be improve please let me know.
 
But I still cannot build-up the project on github and in my vps(before and after my change), I am sorry that I don't know what is wrong. 
The build process was interupted like the image below:
image

**Comment by iromise** [comment]
@Mz1z Yeah, I also find it several days ago. I will take a look these days to fix this bug.

**Comment by iromise** [comment]
@Mz1z I have fix the issue, could you request to preview it again?

**Comment by Mz1z** [comment]
@iromise Thank you~ I add another different type of junk code this time. If there is anything I need to modify, please let me know~

**Comment by iromise** [comment]
@Mz1z Thanks a lot! Already previewed succeed. See https://642faacbf3499f69a2e897e2--modest-austin-48be4a.netlify.app/reverse/windows/anti-debug/junk-code/#_3.

**Pull request merged**
