### PR TITLE
Add basic knowledge for virtualization and QEMU pwn. Add a simple hardware pwn.

### PR DESCRIPTION
**Pull request by arttnba3**
Add basic knowledge for virtualization and QEMU pwn. Add a simple hardware pwn.

### CODE REVIEW

**Comment by iromise** [comment]
@arttnba3 Great work, I will take a look these days!

**Comment by arttnba3** [comment]
@iromise 😢 How long will the review take? It seems that you're busy in recent days.

**Comment by iromise** [comment]
@arttnba3 Sorry for so late, I will take a review this weekend.

**Comment by iromise** [comment]
Good work, merged!

**Pull request merged**
